"""fix Profile.first_name field

Revision ID: 103042591b5e
Revises: 55bc4acb0bb1
Create Date: 2025-04-22 20:41:20.467963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103042591b5e'
down_revision: Union[str, None] = '55bc4acb0bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.drop_column('profiles', 'firs_tname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('firs_tname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'first_name')
    # ### end Alembic commands ###
