"""make role titles unique

Revision ID: 3a9349c39ef0
Revises: 103042591b5e
Create Date: 2025-04-22 21:53:57.080452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9349c39ef0'
down_revision: Union[str, None] = '103042591b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_title'), 'roles', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_title'), table_name='roles')
    # ### end Alembic commands ###
