"""init storage-db structure

Revision ID: d4c9f678730a
Revises: 
Create Date: 2025-10-26 00:38:36.823973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c9f678730a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('prev_chapter', sa.Uuid(), nullable=True),
    sa.Column('next_chapter', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['next_chapter'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['prev_chapter'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.SmallInteger(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('prev_chunk', sa.Uuid(), nullable=True),
    sa.Column('next_chunk', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_chunk'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['prev_chunk'], ['chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks')
    op.drop_table('chapters')
    # ### end Alembic commands ###
